# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.1.8
_src_path: https://github.com/calliecameron/copier-template
author_name: Callie Cameron
copyright_start_year: '2016'
exports_requirements_txt: false
github_repo: calliecameron/dotfiles
max_python_version: '3.12'
min_python_version: '3.12'
project_name: Dotfiles
user_has_css: false
user_has_html: false
user_has_javascript: false
user_uses_pytest: false
