# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.1.1
_src_path: https://github.com/calliecameron/copier-template
author_name: Callie Cameron
copyright_start_year: '2016'
exports_requirements_txt: false
github_repo: calliecameron/dotfiles
is_python_package: false
project_name: Dotfiles
project_version: 0.0.0
python_line_length: 88
user_has_css: false
user_has_html: false
user_has_javascript: false
user_uses_pytest: false
