[project]
name = "dotfiles"
version = "0.0.0"
requires-python = "==3.12.3"
dependencies = []

[dependency-groups]
dev = [
    "mypy==1.17.1",
    "ruff==0.12.11",
]

[tool.mypy]
scripts_are_modules = true
python_version = "3.12"

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "C90",
    "D",
    "EM",
    "FBT",
    "INP",
    "PLR0912",
    "PLR0913",
    "PLR0915",
    "PT",
    "PTH",
    "PYI025",
    "S",
    "T20",
    "TRY003",
]
