[tool.black]
line-length = 100

[tool.isort]
profile = "black"
line_length = 100

[tool.mypy]
scripts_are_modules = true

[tool.pylint.'MESSAGES CONTROL']
disable = "consider-using-f-string,duplicate-code,invalid-name,missing-docstring,too-many-instance-attributes"
enable = "unused-argument"

[tools.pylint.FORMAT]
max-line-length = 100
