export XDG_DATA_DIRS="${PACKAGE_INSTALL_DIR}/share:${XDG_DATA_DIRS}"
export PATH="${PACKAGE_INSTALL_DIR}/bin:${PATH}"
export PYTHONPATH="${PACKAGE_INSTALL_DIR}/lib/python3.5/site-packages:${PYTHONPATH}"
export DOTFILES_GNUCASH_BASE="${PACKAGE_INSTALL_DIR}"
