export DOTFILES_ZONEEDIT_HOST="${DOTFILES_ETC_DIR}/zoneedit-host"
export DOTFILES_ZONEEDIT_USERNAME="${DOTFILES_ETC_DIR}/zoneedit-username"
export DOTFILES_ZONEEDIT_PASSWORD="${DOTFILES_ETC_DIR}/zoneedit-password"
